ipython_view: Handle ANSI escape codes related to bg color
Similar to

    commit 3048bea3bf76aea6851e8320f1795a984fbe72e0
    Date:   Thu Jul 28 02:26:15 2022 +0200

        ipython_view: Add more ANSI color cases

, add handling for more ANSI escape codes according to
the meaning described at [1]. The newly added ones have to
do with handling of background color and were
seen used (and causing exceptions due to not being
handled) on Debian testing when using accerciser with
ipython3 8.5.0-4 and typing e.g. expressions that
return an `AttributeError`, like the following:

    ''.nonExistingMethod()

or

    dummy = ''
    dummy.nonExistingMethod()

Instead of running into a `ValueError` in the `gtk.TextView` like

    In [1]: ''.nonExistingMethod()
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    Cell In [1], line 1
    ----> 1
    Traceback (most recent call last):
      File "/home/michi/temp/accerciser/share/accerciser/plugins/ipython_view.py", line 522, in _showReturned
        self._write('\n'+text)
      File "/home/michi/temp/accerciser/share/accerciser/plugins/ipython_view.py", line 454, in _write
        self.text_buffer.insert_with_tags_by_name(self.text_buffer.get_end_iter(),
      File "/usr/lib/python3/dist-packages/gi/overrides/Gtk.py", line 784, in insert_with_tags_by_name
        raise ValueError('unknown text tag: %s' % tag)
    ValueError: unknown text tag: 38;5;124;43
      Cell In [2], line 2
        ---------------------------------------------------------------------------
                                                                                   ^
    SyntaxError: invalid syntax

, this now shows the expected error in full, with the
"''.nonExistingMethod()" using yellow background color,
as happens when typing the same commands in
a standalone IPython shell:

    In [1]: ''.nonExistingMethod()
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    Cell In [1], line 1
    ----> 1 ''.nonExistingMethod()

    AttributeError: 'str' object has no attribute 'nonExistingMethod'
    In [2]:

Given that black is already used for the default foreground color ('39),
this uses white for the default background color ('49'),

[1] https://en.wikipedia.org/wiki/ANSI_escape_code